### ISSUE TITLE
thank you for sharing - I've modified it to suit my needs

### ISSUE THREAD

**Issue by kamigerami** [garystafford/foreman-vagrant#8]
Hi,

Just wanted to thank you for sharing your work on this project and let you know that I've forked it and modified it to use ansible provisioner instead of shell scripts.

I've also linked to your Github in my README.

If you like to have a look at my modified version of it - you can find it here : 

https://github.com/kamigerami/vagrant_foreman_puppet

Cheers.

**Comment by garystafford** [comment]
Thank you for the email. I will pull a copy and try. We are all puppet and
chef but I'd like to try ansible for sure.

On Thursday, October 22, 2015, Kamjar Gerami notifications@github.com
wrote:

> Hi,
> 
> Just wanted to thank you for sharing your work on this project and let you
> know that I've forked it and modified it to use ansible provisioner instead
> of shell scripts.
> 
> I've also linked to your Github in my README.
> 
> If you like to have a look at my modified version of it - you can find it
> here :
> 
> https://github.com/kamigerami/vagrant_foreman_puppet
> 
> Cheers.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/garystafford/foreman-vagrant/issues/8.

## 

Regards,
Gary A. Stafford
